### ISSUE TITLE
zou prima kunnen zijn

### ISSUE THREAD

**Issue by Theo-denBlanken** [tigomiddelkoop/fro-bewijzenmap21#7]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
lleLinkjesArr[num].classList.add('nav--actief'); 
```

URL: https://github.com/tigomiddelkoop/fro-bewijzenmap21/blob/master/smoothscrollingJS/script/script.js

Feedback: maar er is geen CSS geschreven voor .nav--actief. Er si dus geen visueel gevolg: het linkje krijgt nog steeds geen oogje te zien![](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f2ef75f651926ec42b1e9b57bf2a4ded2a67ffe5","path":"smoothscrollingJS/script/script.js","reviewer":"Theo-denBlanken"}')

**Comment by tigomiddelkoop** [comment]
Deze issue is gefixt in !8432290
